=== OdeiRZ/XML_EXPORTER/agenda.dtd
<!ELEMENT agenda (contacto)*>
<!ELEMENT contacto (nombre, apellidos, fnacimiento?, email?, telefonos, direccion?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fnacimiento (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefonos (telefono)+>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle?, bloque?, letra?, ciudad?, provincia?, pais?, cp?)?>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT bloque (#PCDATA)>
<!ELEMENT letra (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ATTLIST contacto id ID #REQUIRED>
<!ATTLIST telefono tipo (fijo|movil) #IMPLIED>

=== OdeiRZ/XML_EXPORTER/agenda.xml
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacto>
        <nombre>Odei</nombre>
		<apellidos>Riveiro</nombre>
		<fnacimiento>22/12/1987</fnacimiento>
		<email>odei.riveiro@zafra.com</email>
        <telefonos>
            <telefono tipo="fijo">953000000</telefono>
            <telefono tipo="movil">666666666</telefono>
        </telefonos>
        <direccion ciudad="Linares" provincia="Jaén" calle="Salvador Dalí" bloque="9B" piso="2A" />
        <empresa sector="informatica">FAMOSAWEB</empresa>
    </contacto>
    <contacto>
        <nombre>Pedro</nombre>
		<apellidos>Perico Pipete</nombre>
		<fnacimiento>04/06/1993</fnacimiento>
		<email>pedro.perico@pipete.com</email>
        <telefono tipo="movil">616161616</telefono>
        <direccion ciudad="Andújar" provincia="Jaén" calle="Juan Bosco" bloque="1C" piso="4B" />
        <empresa sector="electronica">ENERGY SISTEM SOYNTEC S.A.</empresa>
    </contacto>
</agenda>

=== OdeiRZ/XML_EXPORTER/public/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<?xml-stylesheet href="agenda.xsl" type="text/xsl"?>
<agenda>
    <contacto id="_1">
        <nombre>Odei</nombre>
		<apellidos>Riveiro Zafra</apellidos>
		<fnacimiento>22/12/1987</fnacimiento>
		<email>odei.riveiro@zafra.com</email>
		<telefonos>
			<telefono tipo="fijo">953000000</telefono>
			<telefono tipo="movil">666666666</telefono>
		</telefonos>
		<direccion>
			<calle>Salvador Dalí</calle>
			<bloque>9B</bloque>
			<letra>2A</letra>
			<ciudad>Linares</ciudad>
			<provincia>Jaén</provincia>
			<pais>España</pais>
			<cp>23700</cp>
		</direccion>
    </contacto>
    <contacto id="_2">
        <nombre>Andrea</nombre>
		<apellidos>Marcos Requena</apellidos>
		<fnacimiento>04/06/1983</fnacimiento>
		<email>andrea.marcos@requena.com</email>
		<telefonos>
			<telefono tipo="movil">616161616</telefono>
		</telefonos>
    </contacto>
    <contacto id="_3">
        <nombre>Juan Antonio</nombre>
		<apellidos>Rodriguez</apellidos>
		<fnacimiento>12/01/2000</fnacimiento>
		<telefonos>
			<telefono tipo="fijo">999888777</telefono>
		</telefonos>
		<direccion>
			<calle>Juan Bosco</calle>
			<bloque>1C</bloque>
			<letra>4B</letra>
			<ciudad>Andújar</ciudad>
			<provincia>Jaén</provincia>
			<pais>España</pais>
			<cp>23740</cp>
		</direccion>
    </contacto>
</agenda>
